"domain_suffix": [
  //steam-云服务
  "steamcloud-hkg.oss-accelerate.aliyuncs.com",//aliyun
  "steamcloud-sgp.oss-accelerate.aliyuncs.com",//aliyun
  "steamcloud-sg.s3.dualstack.ap-southeast-1.amazonaws.com",//AWS-新加坡
  "steamcloud-tyo.s3.dualstack.ap-northeast-1.amazonaws.com",//AWS-东京
  "steamcloud-eu-ams.storage.googleapis.com",//Google
  "steamcloud-eu-fra.storage.googleapis.com",//Google
  "steamcloud-finland.storage.googleapis.com",//Google
  "steamcloud-saopaulo.storage.googleapis.com",//Google
  "steamcloud-singapore.storage.googleapis.com",//Google
  "steamcloud-sydney.storage.googleapis.com",//Google
  "steamcloud-taiwan.storage.googleapis.com",//Google
  "steamcloud-ugc.storage.googleapis.com",//Google
  "steamcloud-eu.storage.googleapis.com",//Google
  "steamcloudams.blob.core.windows.net",//Azure
  "steamcloudams2.blob.core.windows.net",//Azure
  "steamclouddub.blob.core.windows.net",//Azure
  "steamcloudfrankfurt.blob.core.windows.net",//Azure
  "steamcloudlrsuswest.blob.core.windows.net",//Azure
  "steamcloudsaopaulo.blob.core.windows.net",//Azure
  "steamcloudsg.blob.core.windows.net",//Azure
  "steamclouduseast.blob.core.windows.net",//Azure
  //steam-登录(cm服务器)
  ".cm.steampowered.com",
  ".steamserver.net"
  //steam-客服页面
  "help.steampowered.com",
  //steam-客户端ipv6测试
  "ipv6check-http.steamserver.net",
  "ipv6check-udp.steamserver.net",
  "ipv6check-http.steamcontent.com",
  "ipv6check-udp.steamcontent.com",
  //steam-客户端更新
  "media.steampowered.com",//a
  "media.st.dl.eccdnx.com",//b
  //steam-游戏截图上传-cn
  "steamcloud-ugc-hkg.oss-accelerate.aliyuncs.com",
  //steam-聊天图片/游戏截图上传-global
  "steamcloud-ugc.storage.googleapis.com",
  //steam-下载(新流云-cn生效)
  "dl.steam.clngaa.com",
  //steam-下载(白云山-cn生效)
  "st.dl.eccdnx.com",
  "st.dl.bscstorage.net",
  "trts.baishancdnx.cn",
  "st-bak.viv.wanwang.space",
  //steam-下载(阿里云-cn生效)
  "cdn-ali.content.steamchina.com",
  "xz.pphimalayanrt.com",
  "lv.queniujq.cn",
  "alibaba.cdn.steampipe.steamcontent.com",
  //steam-下载(网宿-cn生效)
  "cdn-ws.content.steamchina.com",
  //steam-下载(腾讯-cn生效)
  "cdn-qc.content.steamchina.com",
  //steam-下载/社区实况直播(Vavle-非cn生效)
  ".steamcontent.com",
  //steam-下载(akamai-非cn生效)
  "steampipe.akamaized.net",
  "steampipe-kr.akamaized.net",
  "steampipe-partner.akamaized.net",
  //steam-下载(网宿国际-非cn生效)
  "steam.eca.qtlglb.com",
  "steam.naeu.qtlglb.com",
  "steam.ru.qtlglb.com",
  //steam-下载(edgecast-非cn生效)
  "edge.steam-dns.top.comcast.net",
  //steam-商店/购物车
  "store.steampowered.com",
  "checkout.steampowered.com",
  //steam-客户端api
  "api.steampowered.com",
  //steam-好友列表
  "steam-chat.com",
  //steam-图片/视频/静态资源[聊天/商店/社区/创意工坊](cloudflare)
  "cdn.cloudflare.steamstatic.com",
  "community.cloudflare.steamstatic.com",
  "store.cloudflare.steamstatic.com",
  "video.cloudflare.steamstatic.com",
  "avatars.cloudflare.steamstatic.com",
  "dfs.cloudflare.steamstatic.com",
  "clan.cloudflare.steamstatic.com",
  //steam-图片/视频/静态资源[聊天/商店/社区/创意工坊](akamai)
  "steamstore-a.akamaihd.net",
  "steamusercontent-a.akamaihd.net",
  "steamcommunity-a.akamaihd.net",
  "steamcdn-a.akamaihd.net",
  "steamuserimages-a.akamaihd.net",
  "community.akamai.steamstatic.com",
  "avatars.akamai.steamstatic.com",
  "community.steamstatic.com",
  "avatars.steamstatic.com",
  "cdn.steamstatic.com",
  //steam-弹窗新闻页图片
  "cdn.akamai.steamstatic.com",
  //steam-商店网页CSS/JS脚本(白山云-cn)
  "store.st.dl.eccdnx.com",
  //steam-商店页面图片/视频加载(白山云-cn)
  "media.st.dl.eccdnx.com",
  "avatars.st.dl.eccdnx.com",
  "clan.st.dl.eccdnx.com",
  //steam-商店页面图片/视频加载(网宿-cn)
  "cdn.steamstatic.com.8686c.com",
  //steam-创意工坊(akamai-国际)
  "upos-hz-mirrorakam.akamaized.net",
  "steamusercontent-a.akamaihd.net",
  //steam-work
  "partner.steamgames.com",
  //steam-电影/动画(库中)
  "steamvideo-a.akamaihd.net",
  //steam-TV/社区实况直播(白云山-cn)
  "broadcast.st.dl.eccdnx.com",
  //steam-TV直播(akamai-国际)
  "steambroadcast.akamaized.net",
  //steam-社区
  "steamcommunity.com",
  //完美世界
  "csgo.wmsj.cn",
  "dota2.wmsj.cn",
  "wmsjsteam.com",
  "wanmei.com",
  ]